;; 冒泡排序

(defun bubble-sort/arr (arr)
  (let ((flag nil)
		(end (1- (length arr))))
	(do ()
		(flag arr)
	  (setf flag t)
	  (do ((i 1 (+ i 1))
		   (j 0 (+ j 1)))
		  ((> i end) arr)
		(cond ((< (aref arr i)
				  (aref arr j))
			   (rotatef (aref arr i) (aref arr j))
			   (setf flag nil))
			  (t nil))))))	
